### PR TITLE
Create postcard

### PR DESCRIPTION
**Pull request by seankross**

### CODE REVIEW

**Comment by jjallaire** [comment]
We are hoping to update the distill docs with directions on how to include postcards. If you end up merging https://github.com/seankross/postcards/pull/20 then we'll just say "create a postcard via New R Markdown... document". Otherwise, we'll instruct people to use the `create_postcard()` function once this PR is merged. LMK what you have in mind and I'll update the docs accordingly.

**Comment by seankross** [comment]
You should instruct people to use `create_postcard()` and I am going to do the same in the postcards documentation. Thank you again for your contributions to this package and for supporting its use with distill, which is a package and project I admire very much. If you want to add yourself as a coauthor of this package feel free to send me a PR for the description file.

**Comment by jjallaire** [comment]
Great, thanks! Here are the updated docs on using postcards with distill: https://rstudio.github.io/distill/website.html#postcards

**Comment by seankross** [comment]
Looks great! Let me know if there are any other changes you would like to see before I send the updated version of this package to CRAN.

**Comment by jjallaire** [comment]
LGTM. @apreshill Any change you'd want to see here?

**Comment by arnold-c** [comment]
It could be that I'm missing something here, but when I follow the distill instructions, unfortunately I lose the nav bar when I open the postcards page (it doesn't matter what template I use). Is there a way around this, as postcards would make a great landing page for a personal website?

**Pull request merged**
